### ISSUE TITLE
How to get the current index of displayed image?

### ISSUE THREAD

**Issue by luhluh-17** [hd-motion/flutter_imageview_360#1]

**Comment by harpreetseera** [comment]
The current version does not have the privilege to provide the index of the image being currently displayed. This property will be added in the next version and it will be rolled out soon.

**Comment by harpreetseera** [comment]
The new version of [imageview360](https://pub.dev/packages/imageview360) provides the callback for image index changed. @luhluh-17  this would be the solution to your problem.
