### ISSUE TITLE
Images Download From internet can't be displayed

### ISSUE THREAD

**Issue by NouranAmr** [hd-motion/flutter_imageview_360#2]
I tried to download an images and then add them to an array , pass this array to ImageView360 widget ,
but it take only AssetImage, so there i must have an images first in assets .
How to do this?

**Comment by CarlosCabarcos** [comment]
You can edit the ImageView360 class and turn `final List<AssetImage> imageList;` into `final List<ImageProvider> imageList`; so it will also accept NetworkImages, MemoryImages, etc. Honestly, it should be like that by default, it's way more versatile.

**Comment by harpreetseera** [comment]
Hi, thanks for pointing it out. You can check out [version 1.2.0](https://pub.dev/packages/imageview360) as it supports ImageProvider as a param in imageList. For better experience make sure, the images to be displayed are cached.
