### ISSUE TITLE
When rotating through the 360 carousel the image appears and disappears (blinks)

### ISSUE THREAD

**Issue by CarlosCabarcos** [hd-motion/flutter_imageview_360#3]
I didn't understand what on earth was going on until I discovered a property I didn't know about that I believe is not set properly. In the build function:

```
  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        GestureDetector(
          onHorizontalDragEnd: (details) {
            localPosition = 0.0;
          },
          onHorizontalDragUpdate: (details) {
            // Swipe check,if allowed than only will image move
            if (widget.allowSwipeToRotate) {
              if (details.delta.dx > 0) {
                handleRightSwipe(details);
              } else if (details.delta.dx < 0) {
                handleLeftSwipe(details);
              }
            }
          },
          child: Image(image: widget.imageList[rotationIndex]),
        ),
      ],
    );
  }
```
`child: Image(image: widget.imageList[rotationIndex]),` should be changed to `child: Image(gaplessPlayback: true, image: widget.imageList[rotationIndex]),`.

Perhaps on a Samsung Galaxy S10 or an iPhone 10 you can't even notice it cause they're so fast, but on the Android emulator or a mid-range Android device, it's very clearly noticeable.

gaplessPlayback: true.

**Comment by harpreetseera** [comment]
Hi, thanks for pointing it out. You can check out version 1.2.0 as the issue has been fixed in the version
