### ISSUE TITLE
Set starting index for 360 sequence

### ISSUE THREAD

**Issue by onlyamessenger** [hd-motion/flutter_imageview_360#4]
I don't see an option for this, but can we possibly set a starting index for the 360 sequence? So for example, if I want to start the sequence at the 10th image instead of the 1st, on the initial load of the widget.

**Comment by MustafaDev-shaikh** [comment]
@ascendedco  Brother Did You Solve this issue.??

@harpreetseera  Can you please update this library for index

**Comment by harpreetseera** [comment]
@ascendedco , @MustafaDev-shaikh I think this can be managed easily as we can rearrange the the sequence of the images in the imageList to be provided to the imageview360 widget. 

Let's suppose if we need to start the loading from 4th image then we should pass the image list with the 10 image on first index and following it when the list ends the rest images should be append at the back.
```
Instead of this: [ img1,img2,img3,img4,img5,img6,img7,img8,img9,img10]
Pass this: [img4,img5,img6,img7,img8,img9,img10,img1,img2,img3]
```

**Comment by onlyamessenger** [comment]
> @ascendedco Brother Did You Solve this issue.??
> 
> @harpreetseera Can you please update this library for index

See @harpreetseera response above. This is how I solved the issue way back 😄

**Comment by onlyamessenger** [comment]
Thank you this can be closed.

**Comment by MustafaDev-shaikh** [comment]
@harpreetseera  Thanks for the suggestion. But my problem is when I rotate image and the index of the image is 5th position and  I select different Image for example different color of Car Black or Blue. So on click new list the position should be  start from 5th  of previous list.
